= Projet de la SAÉ 2.01- 2.05

:toc:

== Description générale du projet 

Dans ce projet, notre objectif sera de développer une application JAVA-Oracle de geston des comptes clients pour remplacer plusieurs outils obsolètes. Nous travaillerons à partir d'une application existante "Daily bank" que nous adapterons aux nouveaux besoins de la banque.

Liste des participants :

* JOLAS Alex
* NARAYANIN Noa
* DANG Hai Son
* PODA Nicolas

Ce projet a été réalisé dans le cadre d'une SAÉ à l'IUT de Blagnac.

== Statut du projet 

Projet en cours de réalisation. 


== Instrcution pour l'installation et l'utilisation 

Le projet est en cours de réalisation, il est donc pour le moment impossible d'installer ou d'utiliser quoi que ce soit.

== Liste de technologies utilisées 

* Eclipse IDE for Java Developers
* Microsoft project
* Discord
* Visual Studio Code

== Bugs connus et éventuelles corrections apportées

Le projet est en cours de réalisation.

== FAQ 

...

== Droits d'auteurs et infomations sur la licence

...


