= SAE 2.01 - Document technique 
:toc:

*Équipe :* Jolas Alex - Poda Nicolas - Dang Hai Son - Narayanin Noa

*Version :* 1.0

*Date :* 25/05/2022

:toc:

== Sommaire

=== Description du projet



* Equipe
 ** DANG Hai Son
 ** JOLAS Alex
 ** NARAYANIN Noa
 ** PODA Nicolas
 
* Contexte du projet

Le projet "Daily Bank" est un projet informatique de taille moyenne qui compte 4 personnes. Notre équipe travaille à l'IUT de Blagnac dans le but de restructurer les services bancaires de la banque DailyBank.

* Objectifs du projet 

La demande de la banque DailyBank est de rendre fonctionnelle leur application en implémentant tout ce qui est nécessaire.

Il y a plusieurs tâches à effectuer : il faut donner la possibilité au guichetier de générer un relevé mensuel d'un compte en PDF, et de gérer les prélèvements automatiques. Il faut donner la possibilité au chef d'agence d'effectuer un débit exceptionnel, simuler un emprunt, et simuler une assurance d'emprunt.

=== Plan



== Présentation rapide de l'application

=== Use case global

=== Diagramme de classe des données global

== Architecture

=== Architecture générale en termes de sous-systèmes (poste client, serveurs, ...) et rôle de chaque élément

=== Ressources externes utilisées et rôles (.jar, ...)

=== Structuration en packages de l'application documentée. Principes retenus pour cette structuration

Au sein de l'application, il y a différents packages. Un package nommé "application", représente le package principal. Au sein de celui-ci, il a d'autres packages :

* application.control : c'est le package dans lequel les sous-programmes utiles, qui sont appelés dans la vue, sont stockés. 
* application.view : c'est le package qui représente la vue de l'application. Au sein de celui-ci, il y a tous les "controllers", c'est-à-dire les classes qui nous permettent de contrôler le contenu de chaque fenêtre. Il y a aussi les fichiers FXML, qui nous permettent de gérer le design de chaque fenêtre.

* application.tools : c'est le package qui contient les outils nécessaires pour développer le programme, tels que les catégories d'opérations, les différents modes d'édition, les messages d'alerte

Il y a aussi différents packages liés aux "modèles". 

* model.data : c'est le package dans lequel les classes principales, telles que le client, l'agence bancaire, le compte courant, l'employé, l'opération et le type d'opération sont stockés. Dans chaque classe, il y a les constrcuteurs, ainsi qu'une méthode "toString".

* model.orm : c'est le package qui permet le lien entre la base de données Oracle et le code Java. Au sein de celui-ci, sont contenues les classes nous permettant de réaliser des sélections, des insertions, ou encore des appels de méthode dans la base de données Oracle.

* model.orm.exception : c'est dans ce package que toutes les exceptions liées à la relation entre le code et la base de données sont stockés. Par exemple, les erreurs d'accès à la base de données.

=== Éléments essentiels à connaître, spécificités nécessaires à la mise en oeuvre du développement





== Fonctionnalités de la v1






== Maquettes d'écran

Les maquettes d'écran sont disponibles dans https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Doc-User-V1.adoc[le document utilisateur]

 
