= SAE 2.01 - Document technique 
:toc:

*Équipe :* Jolas Alex - Poda Nicolas - Dang Hai Son - Narayanin Noa

*Version :* 1.0

*Date :* 25/05/2022

:toc:

== Sommaire

=== Description du projet



* Equipe
 ** DANG Hai Son
 ** JOLAS Alex
 ** NARAYANIN Noa
 ** PODA Nicolas
 
* Contexte du projet

Le projet "Daily Bank" est un projet informatique de taille moyenne qui compte 4 personnes. Notre équipe travaille à l'IUT de Blagnac dans le but de restructurer les services bancaires de la banque DailyBank.

* Objectifs du projet 

La demande de la banque DailyBank est de rendre fonctionnelle leur application en implémentant tout ce qui est nécessaire.

Il y a plusieurs tâches à effectuer : il faut donner la possibilité au guichetier de générer un relevé mensuel d'un compte en PDF, et de gérer les prélèvements automatiques. Il faut donner la possibilité au chef d'agence d'effectuer un débit exceptionnel, simuler un emprunt, et simuler une assurance d'emprunt.


== Présentation rapide de l'application

=== Use case global

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/diagramme_ucv1.svg[diagramme_ucv1]

=== Diagramme de classe des données global

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/diagramme_classes_v1.svg[Diagramme de classes]
== Architecture

=== Architecture générale en termes de sous-systèmes (poste client, serveurs, ...) et rôle de chaque élément

* *Poste client*

Un poste client correspond à un ordinateur utilisé par un employé de l'agence bancaire. Son rôle est de peremettre à l'employé de gérer les données relatives aux clients, aux comptes, etc. 

* *Serveurs*

Le serveur de base de données permet de stocker, extraire et gérer toutes les informations relatives aux clients, à leurs comptes, aux opérations effectuées, etc.

Il permet aussi de gérer la mise à jour des données, et donne un accès à cette base de données aux programmeurs.

=== Ressources externes utilisées et rôles 

Lorsque le développement de la version finale aura été réalisé, un fichier *.jar*, permettant de lancer l'application, sera généré. Grâce à celui-ci, tous les fichiers liés au projet créé, seront stockés. Il suffira alors d'exécuter une ligne de commandes pour lancer l'application.

De plus, la librairie *"ojdbc6.jar"* sera utilisée. Elle permet d'établir une connexion entre la base de données Oracle, et le code Java.

=== Structuration en packages de l'application documentée. Principes retenus pour cette structuration

Au sein de l'application, il y a différents packages. Un package nommé "application", représente le package principal. Au sein de celui-ci, il a d'autres packages :

* *application.control* : c'est le package dans lequel les sous-programmes utiles, qui sont appelés dans la vue, sont stockés. 
* *application.view* : c'est le package qui représente la vue de l'application. Au sein de celui-ci, il y a tous les "controllers", c'est-à-dire les classes qui nous permettent de contrôler le contenu de chaque fenêtre. Il y a aussi les fichiers FXML, qui nous permettent de gérer le design de chaque fenêtre.

* *application.tools* : c'est le package qui contient les outils nécessaires pour développer le programme, tels que les catégories d'opérations, les différents modes d'édition, les messages d'alerte

Il y a aussi différents packages liés aux "modèles". 

* *model.data* : c'est le package dans lequel les classes principales, telles que le client, l'agence bancaire, le compte courant, l'employé, l'opération et le type d'opération sont stockés. Dans chaque classe, il y a les constrcuteurs, ainsi qu'une méthode "toString".

* *model.orm* : c'est le package qui permet le lien entre la base de données Oracle et le code Java. Au sein de celui-ci, sont contenues les classes nous permettant de réaliser des sélections, des insertions, ou encore des appels de méthode dans la base de données Oracle.

* *model.orm.exception* : c'est dans ce package que toutes les exceptions liées à la relation entre le code et la base de données sont stockés. Par exemple, les erreurs d'accès à la base de données.


=== Éléments essentiels à connaître, spécificités nécessaires à la mise en oeuvre du développement

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/sequence_systeme_global.svg[Diagramme de séquence]


== Fonctionnalités de la v1

=== Créditer un compte

* *Partie de use case réalisé*

Dans le use case, un cas s'utilisation nommé "Créditer un compte" a été créé. Il a été relié à l'acteur "Guichetier".

* *Partie du diagramme de classe de données nécessaires*

Les parties du diagramme de classe de données nécessaires sont la classe CompteCourant, la classe Operation et la classe TypeOperation.


* *Copies écrans principales de la fonctionnalité* 

Les copies écrans sont disponibles dans https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Doc-User-V1.adoc[le document utilisateur]

* *Classes impliquées dans chaque package* 

Package application.control : OperationEditorPane, OperationsManagement

Package application.tools : CategorieOperation, ConstantesIHM

Package application.view : OperationEditorPaneController, OperationsManagementController

Package model.data : Operation, TypeOperation

Package model.orm : AccessOperation, AccessTypeOperation, LogToDatabase

Package model.orm.exception : toutes les classes sont impliquées

* *Eléments essentiels à connaitre, spécificités nécessaires à la mise en oeuvre du développement*

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/sequence_crediter.svg[sequance_crediter]



===  Débiter un compte


* *Partie de use case réalisé*



Dans le use case, un cas s'utilisation nommé "Débiter un compte" a été créé. Il a été relié à l'acteur "Guichetier".


* *Partie du diagramme de classe de données nécessaires* 

Les parties du diagramme de classe de données nécessaires sont la classe CompteCourant, la classe Operation et la classe TypeOperation.

* *Copies écrans principales de la fonctionnalité* 

Les copies écrans sont disponibles dans https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Doc-User-V1.adoc[le document utilisateur]


* *Classes impliquées dans chaque package* 

Package application.control : OperationEditorPane, OperationsManagement

Package application.tools : CategorieOperation, ConstantesIHM

Package application.view : OperationEditorPaneController, OperationsManagementController

Package model.data : Operation, TypeOperation

Package model.orm : AccessOperation, AccessTypeOperation, LogToDatabase

Package model.orm.exception : toutes les classes sont impliquées


* *Eléments essentiels à connaitre, spécificités nécessaires à la mise en oeuvre du développement*

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/sequence_debiter.svg[sequence_debiter]


=== Créer un compte

* *Partie de use case réalisé*

Dans le use case, un cas s'utilisation nommé "Créer un compte" a été créé. Il a été relié à l'acteur "Guichetier".

* *Partie du diagramme de classe de données nécessaires* 

La partie du diagramme de classe de données nécessaire est la classe CompteCourant.

* *Copies écrans principales de la fonctionnalité* 

Les copies écrans sont disponibles dans https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Doc-User-V1.adoc[le document utilisateur]

* *Classes impliquées dans chaque package* 

Package application.control : CompteEditorPane, ComptesManagement

Package application.view : CompteEditorPaneController, ComptesManagementController

Package model.data : CompteCourant

Package model.orm : AccessCompteCourant, LogToDatabase

Package model.orm.exception : toutes les classes sont impliquées

* *Eléments essentiels à connaitre, spécificités nécessaires à la mise en oeuvre du développement*

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/sequence_creer_compte.svg[sequence_creer_compte]

=== Effectuer un virement de compte à compte

* *Partie de use case réalisé*

Dans le use case, un cas s'utilisation nommé "Effectuer un virement de compte à compte" a été créé. Il a été relié à l'acteur "Guichetier".


* *Partie du diagramme de classe de données nécessaire* 

Les parties du diagramme de classe de données nécessaires sont la classe CompteCourant, la classe Operation et la classe TypeOperation.

* *Copies écrans principales de la fonctionnalité*

Les copies écrans sont disponibles dans https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Doc-User-V1.adoc[le document utilisateur]


* *Classes impliquées dans chaque package* 

Package application.control : OperationEditorPane, OperationsManagement

Package application.tools : CategorieOperation, ConstantesIHM

Package application.view : OperationEditorPaneController, OperationsManagementController

Package model.data : Operation, TypeOperation

Package model.orm : AccessOperation, AccessTypeOperation, LogToDatabase

Package model.orm.exception : toutes les classes sont impliquées


* *Eléments essentiels à connaitre, spécificités nécessaires à la mise en oeuvre du développement*

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/sequence_virement.svg[sequence_virement] 

=== Clôturer un compte

* *Partie de use case réalisé*

Dans le use case, un cas s'utilisation nommé "Clôturer un compte" a été créé. Il a été relié à l'acteur "Guichetier".

* *Partie du diagramme de classe de données nécessaires*

La partie du diagramme de classe de données nécéssaire est la classe CompteCourant.

* *Copies écrans principales de la fonctionnalité* 

Les copies écrans sont disponibles dans https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Doc-User-V1.adoc[le document utilisateur]


* *Classes impliquées dans chaque package* 

Package application.control : ComptesManagement

Package application.view : ComptesManagementController

Package model.data : CompteCourant

Package model.orm : AccessCompteCourant, LogToDatabase

Package model.orm.exception : toutes les classes sont impliquées

* *Eléments essentiels à connaitre, spécificités nécessaires à la mise en oeuvre du développement*

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/sequence_cloturer_compte.svg[sequence_cloturer_compte]

=== Gérer les employés

* *Partie de use case réalisé*

Dans le use case, un cas s'utilisation nommé "Gérer les employés" a été créé. Il a été relié à l'acteur "Chef d'agence".


* *Partie du diagramme de classes de données nécessaires* 

La partie du diagramme de classes de données nécessaire est la classe Employe. 


* *Copies écrans principales de la fonctionnalité* 

Les copies écrans sont disponibles dans https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Doc-User-V1.adoc[le document utilisateur]


* *Classes impliquées dans chaque package* 

Package application.control : LoginDialog

Package application.view : LoginDialogController

Package model.data : Employe

Package model.orm : AccessEmploye, LogToDatabase

Package model.orm.exception : toutes les classes sont impliquées


* *Eléments essentiels à connaitre, spécificités nécessaires à la mise en oeuvre du développement*

image::https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Images_doc_tec_v1/sequence_gerer_employes.svg[sequence_gerer_employes]

 
