= SAE 2.01 - Document technique 
:toc:

*Équipe :* Jolas Alex - Poda Nicolas - Dang Hai Son - Narayanin Noa

*Version :* 1.0

*Date :* 25/05/2022

:toc:

== Sommaire

=== Description du projet



* Equipe
 ** DANG Hai Son
 ** JOLAS Alex
 ** NARAYANIN Noa
 ** PODA Nicolas
 
* Contexte du projet

Le projet "Daily Bank" est un projet informatique de taille moyenne qui compte 4 personnes. Notre équipe travaille à l'IUT de Blagnac dans le but de restructurer les services bancaires de la banque DailyBank.

* Objectifs du projet 

La demande de la banque DailyBank est de rendre fonctionnelle leur application en implémentant tout ce qui est nécessaire.

Il y a plusieurs tâches à effectuer : il faut donner la possibilité au guichetier de générer un relevé mensuel d'un compte en PDF, et de gérer les prélèvements automatiques. Il faut donner la possibilité au chef d'agence d'effectuer un débit exceptionnel, simuler un emprunt, et simuler une assurance d'emprunt.

=== Plan



== Présentation rapide de l'application

=== Use case global

=== Diagramme de classe des données global

== Architecture

=== Architecture générale en termes de sous-systèmes (poste client, serveurs, ...) et rôle de chaque élément

=== Ressources externes utilisées et rôles (.jar, ...)

=== Struvcutration et packages de l'application documentée. Principes retenus pour cette structuration

=== Éléments essentiels à connaître, spécificités nécessaires à la mise en oeuvre du développement


== Fonctionnalités




== Maquettes d'écran

Les maquettes d'écran sont disponibles dans https://github.com/IUT-Blagnac/sae2022-bank-2b02/blob/main/documentation/Doc-User-V1.adoc[le document utilisateur]

 
