 
=== CDCU 
revoir les documentations fournies en gestion de projet 

==== Page de garde (Version, date, équipe, projet ...)
elle n'est pas présente

 
==== Sommaire voir quand ce sera plus détaillé mais il manque déjà : 1 une partie analyse de l'existant.
2
Un lien vers le gantt du projet.
Une descrition de l'échancier des livrables.

=== Objectif du projet
L’application doit permettre de gérer des comptes bancaires de dépôt pour des clients préalablement créés. Elle devra permettre de débiter, créditer un compte soit par virement c’est à dire un échange d’argent entre deux comptes distincts mais domiciliés dans le réseau bancaire, soit par une personne physique se présentant devant un guichet.
... cela n'est pas suffisant.


Qui est le client ? Qui sont les utilisateurs de l'application ?

Pour moi deux les guichetiers et les chefs d'agences.
Il faut aussi produire un texte indiquant que les guichetiers pourront créer de nouceaux clients et faire les opétations courante...
Que les chefs d'agences pourront gérer les employé et les opérations exeptionnelles...

L'application commence par une analyse de l'exsitant puis sera découpée en plusieurs versions à la demande du client

==== analyse de l'existant

 
Description du système d’information actuel de l’organisation :
Les processus informatisés ou non, impactés par le projet seront décrits
(à l’aide d’un outil de modélisation).
 ... voir docu gestion de projet
 
 Vous devriez ici avoir les UC de l'existant et vous devriez les commenter...
 
 
==== les contraintes liées au projet


Vous devriez indiquer qu'il y aura un lien avec une base de donnée existante, que l'appli initiale sera fournie en java avec une IHM cpdée en java FX
Que vous devez travailler avec une équipe constituée de ...
Que les échances des différentes version du projet sont ...
...


==== analyse des nouveaux besoins

Indiquer les fonctionnalités qu'on vous a demandé pour la V1


Il faut ici que vous reformulier la demande du client afin de vous assurer que vous avez bien compris.

==== La description de la solution

Un use case commenté peut être une bonne idée.

Une maquette des interfaces...

==== Modalités d’organisation pour la suite du projet

qui fait quoi ici le gant commenté c'est bien

Quels sont les dates de livraison de chaque livrable,

Quelles seront les modalités de la livraison recette, doc...



==== Enveloppe bug
Vous avez un doc de Mme pendaries depuis votre gantt vous avec les heures prévisionnelle de codage de test, de rédaction...
